{
  imports = [
    ./profiles/bitcoin.nix
    ./profiles/desktop.nix
    ./profiles/dev.haskell.nix
    ./profiles/dev.javascript.nix
    ./profiles/dev.nix
    ./profiles/dev.python.nix
    ./profiles/emacs.nix
    ./profiles/finance.nix
    ./profiles/git.nix
    ./profiles/gpg.nix
    ./profiles/irssi.nix
    ./profiles/laptop.nix
    ./profiles/latex.nix
    ./profiles/newsboat.nix
    ./profiles/suckless.nix
    ./profiles/sxhkd.nix
    ./profiles/vim.nix
    ./profiles/work.nix
    ./profiles/zathura.nix
    ./profiles/zsh.nix
  ];
}
