{
  imports = [
    ./profiles/bitcoin.nix
    ./profiles/desktop.nix
    ./profiles/desktop.xfce.nix
    ./profiles/dev.c.nix
    ./profiles/dev.javascript.nix
    ./profiles/dev.lisp.nix
    ./profiles/dev.nix
    ./profiles/dev.python.nix
    ./profiles/dev.scheme.nix
    ./profiles/emacs.nix
    ./profiles/finance.nix
    ./profiles/gfx.nix
    ./profiles/git.nix
    ./profiles/gpg.nix
    ./profiles/im.nix
    ./profiles/latex.nix
    ./profiles/pass.nix
    ./profiles/wechall.nix
    ./profiles/work.nix
  ];
}
