export PS1="\[\e[1m\](\[\e[36m\]\u\[\e[97m\]@\[\e[36m\]\h\[\e[97m\])[\[\e[32m\]\w\[\e[97m\]\$(git_branch)]\n>\[\e[0m\] "

git_branch() {
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\/@\1/'
}

if command -v fzf-share >/dev/null; then
        source "$(fzf-share)/key-bindings.bash"
fi
